### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by Tofutush** [LLK/scratch-desktop#124]
Even though it says "detailed version", but I still don't quite understand how to run Scratch 3.0. Do I just download the release, or clone like you said? How do I run those "npm" stuff?

**Comment by apple502j** [comment]
It depends on how you run Scratch 3.0:
- On browser: see https://github.com/LLK/scratch-gui (see "Installation" and "Running" section)
- On an electron app: This is the correct version for that! see README, "Developer Instructions"

Zip download may be enough for experiments, but for proper development Git is recommended.

Also, before making a Issue, I recommend at least searching for basic knowledge, including Git and Node.js. Just search "how to install node.js" and follow the instructions.

**Comment by cwillisf** [comment]
Hi @Tofutush! If you'd just like to run Scratch 3.0, you can either visit https://scratch.mit.edu/ to run the browser version or download the app at https://scratch.mit.edu/download/

If you'd like to change Scratch 3.0 then I recommend using `git` to clone this repository, then use `npm` and other Node.js tools to work on the code. If you haven't worked with `git` or `npm` or `node` before then Scratch might not be the best project to start with; it's pretty big and complicated. I would recommend reading some documentation and/or starting with some smaller projects to get familiar with `git` and Node.js first, then once you have a little familiarity with those tools you'll be better equipped to dive into Scratch's code.

Since this isn't specifically a problem with the "scratch-desktop" project I'm going to close this issue, but feel free to continue the conversation here if you have more questions. Thanks!
