### ISSUE TITLE
npm link is invalid

### ISSUE THREAD

**Issue by btwise** [LLK/scratch-desktop#175]
Why do I use the `npm link` command in Scratch-Desktop to refer to the local scratch-GUI module, and after `npm install` is executed correctly, the interface I get when I run `npm start` is not the contents of the scratch-GUI I have modified?

**Comment by vovsike** [comment]
I have same issue. Try running `npm start --preserve-symlinks`

**Comment by cwillisf** [comment]
Hi @btwise! If I understand correctly, it sounds like you're running into a quirk of how `npm` works. It turns out that `npm install` removes any links that you might have made, so the best sequence is:

1. `cd scratch-gui`
2. `npm link`
3. `cd ../scratch-desktop`
4. `npm ci` or `npm install`
5. `npm link scratch-gui`
6. `npm start`

If you use `npm install` or `npm ci` for anything in the `scratch-desktop` directory, you'll need to run `npm link scratch-gui` again.

If I've misunderstood, feel free to reopen this issue with more detail. Thanks!
