### ISSUE TITLE
Crashing each time while trying to open Scratch on Windows 11

### ISSUE THREAD

**Issue by nasirkhan** [LLK/scratch-desktop#207]
### Expected Behavior

I installed Scratch from Windows Store. Which I tried to open the application I expected it would open and I will use the editor.

### Actual Behavior

Scratch was crashed each time I tried to open it. 

### Steps to Reproduce

1. Open windows Store and search for Scratch or open https://www.microsoft.com/store/apps/9pfgj25jl6x3?cid=storebadge&ocid=badge
2. Install Scratch from windows store
3. Click on the Open button from the Windows store
4. It may show the blue scratch loader for a second and then it closes. 

### Operating System and Browser
Edition: Windows 11 Home Insider Preview Single Language
Version: Dev
Installed on: 05/‎10/‎2021
OS build: 22471.1000
Experience: Windows Feature Experience Pack 1000.22471.1000.0

### Note

Here I would like to mention that I installed Scratch (Scratch 3.26.0) again by directly downloading it and that worked perfectly.

**Comment by cwillisf** [comment]
Hi @nasirkhan! Thanks for the excellent report!

I found that it works for me on the release version of Windows 11, and since the direct download works for you I'd guess this problem has something to do with the Insider Preview version of Windows 11. I'll close this issue for now on that theory.

If you find that this is still a problem for you if and when you update to the release version, we can re-open this issue. Thanks!
