### ISSUE TITLE
How to modify Scratch desktop version

### ISSUE THREAD

**Issue by sarkaramitabh300** [LLK/scratch-desktop#239]
Hi, I want to change the scratch desktop app's logo and the scratch name, and some other theme modifications, 
the readme is not very clear to me, I am unable to do it, I have also gone through the modding guide but no help, there is nothing mentioned about the scratch desktop app modification,
please point me to a correct source or guide or help me here.

**Comment by cwillisf** [comment]
Hello! We generally only support enhancing the Scratch application, rather than creating alternative versions of it. You're welcome to create alternative versions, of course, but we can't really provide support for that path since it's no longer "Scratch" at that point.

I can give a few general tips, though:

* icons are in the `buildResources` and `src/icon` directories
* the "Scratch" name is listed in `package.json` but might appear in other places as well. You'll probably need to do a search to find all the places.
* to understand the desktop app, I recommend reading about Electron. You can find the Electron-specific code in this repository:
  * `src/main` contains code that runs in the "main" (Node.js-like) process
  * `src/renderer` contains code that runs in the "renderer" (Chromium-like) processes
  * `src/common` contains code that runs in both
