### ISSUE TITLE
wdm failed to compile error when building on Mac

### ISSUE THREAD

**Issue by CmdrNorthpaw** [LLK/scratch-desktop#53]
I am building Scratch Desktop on my Mac, but when I run `npm start` it throws a WDM: failed to compile error. Here are the steps I followed to build the app:

1. I `git clone`d scratch-gui and scratch-desktop
2. I ran `cd scratch-gui` and then `npm install` to installed all the dependencies
3. I ran `git checkout scratch-desktop`
4. I did the `Build_Mode=dist...` thing, but it threw an error, so I run `npm install` again and it went without error.
5. I went into scratch-dektop and ran `npm run fetch` but it threw an error so I rsn `npm install` and it went without errors
6. I ran `npm run start` but wdm refused to compile and no window appeared.

**Comment by cwillisf** [comment]
Hi! To help us figure out what's going wrong, could you please either copy & paste the first error that you see, or post a screenshot of it? If it's a long error message, make sure to include the top of it. Thanks!

I would also recommend running `npm link` in `scratch-gui` and `npm link scratch-gui` in `scratch-desktop`. That's the easiest way to make the "Prepare `scratch-gui`" steps work correctly. Note that you'll need to run `npm link scratch-gui` in `scratch-desktop` after every time you run `npm install`, since [`npm install` removes links](https://github.com/npm/npm/issues/18980).

**Comment by cwillisf** [comment]
I just added a "quick start" section to the "Prepare `scratch-gui`" part of the documentation. Hopefully following this sequence will fix the build for you: https://github.com/LLK/scratch-desktop#prepare-scratch-gui-quick-start

**Comment by cwillisf** [comment]
Hopefully the "quick start" section helps anyone who's still having this kind of trouble. If this continues to be a problem we can reopen this issue but for now I'll close it.
