### ISSUE TITLE
There should be a way to view a privacy policy within the app

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-desktop#97]
### Expected Behavior

It should be possible for a user to view the app's privacy policy inside the app itself, without an Internet connection. This is now required by the Microsoft Store, but in hindsight it's also just a good idea.

### Actual Behavior

The only privacy policy information displayed by the app is on the initial telemetry opt-in/out dialog, which in most cases only appears the first time the app runs.

**Comment by cwillisf** [comment]
While working on the technical aspects of this (opening a new window, etc.) it became clear that there are some design questions we should discuss. Basically, how should the user get to the privacy policy?

The options that first come to my mind are:

1. Add a link into the current "About" window, or
2. Add an option under one of our current menus (maybe under the "File" menu?), or
3. Add a new menu with an item for the privacy policy under it, maybe along with another item for the current "About" window.

I'm certainly open to other proposals, too!

### Current behavior

Right now, clicking on the Scratch logo in the upper left will open an "About" window:

1. ![image](https://user-images.githubusercontent.com/7019101/73477957-0b08fa00-434a-11ea-913f-61991d3e3936.png)
2. ![image](https://user-images.githubusercontent.com/7019101/73477973-11977180-434a-11ea-9ac0-b20245160d4c.png)

Unfortunately it's not very obvious that the Scratch logo does that, and many people probably wouldn't know to click on it if they wanted the version information. For the most part I consider this in its current form to just be an aid for our internal tests.

### What does the policy window look like?

NOTE: the text shown here is in review and is subject to change without warning. This image is only here to show the style and approximate size of the window.

![image](https://user-images.githubusercontent.com/7019101/73478635-4b1cac80-434b-11ea-962a-5e0e16c94166.png)

### What would it look like to add a link in the current "About" window?

Maybe something like this, though we should discuss details:

![image](https://user-images.githubusercontent.com/7019101/73479484-f5490400-434c-11ea-8ad2-11d8d06255b2.png)

### What would it look like to add a new menu?

Maybe something like this, though again we should discuss details. Sorry, I know I used the wrong font but this should get the idea across...

![image](https://user-images.githubusercontent.com/7019101/73480482-d3508100-434e-11ea-9376-26e06cf0d3e4.png)

### What about adding a new item to an existing menu?

We'd probably want to add "About" and "Privacy" items to the "File" menu, since they make more sense there than the "Edit" menu.

### Why not use the macOS standard "About" menu?

Mostly because the top menu bar in macOS has no equivalent in Windows. We could add a menu bar to the top of the main editor window, but that would mean we have two menu bars on the main window.

**Comment by cwillisf** [comment]
@carljbowman @kathymakes: I would love your input on the design thoughts above, including:

- Should the user get to the privacy policy by clicking the Scratch logo, a new item in an existing menu, or a new menu?
- If it's by clicking the Scratch logo:
   - Should the logo first open the current "About" window, which would contain a link to the privacy policy?
   - If so, how should that link be presented?
- If it's a new item in an existing menu or a new menu:
   - What menu should the privacy policy be listed under? ("File"? A new menu?)
   - What should the privacy policy menu item be called?
   - Should the current "About" window be under the same menu? If so, what should that menu item be called?
   - If we're adding a new menu:
      - Where should it be on the menu bar? The rightmost edge? Just to the right of "Edit"? Just to the right of the project title box?
      - Should we add any vertical separator bars?

I'm open to any ideas & input you have, including ideas that aren't like any of the proposals I've mocked up.

**Comment by carljbowman** [comment]
This is great! Thank's @cwillisf for outlining all these ideas! Certainly thought of the macOS route and, similar to your note, I was like "nope there is nothing equivocate on Windows."

**Menu Thoughts**
I agree that the direction of clicking the Scratch logo feels a little obscure. At first I was thinking about adding an "About Scratch" menu item under "File" (e.g. "File > About Scratch"), but wonder if that diving pattern also feels a little obscure. It doesn't quite fit hierarchically under "File". Although, it is enticing because it's its relatively simple. 

Adding a new menu could be the clearest diving pattern, but it's adding more surface level UI which deviates from other versions of Scratch (online version / ChromeOS App). Maybe that is okay though, since the placement is off to the right, which is usually reserved for logged in information on the online version, kinda nice that it's using that unclaimed space rather than changing the parts that are consistent (e.g adding an "About" menu to the right of the "Edit" menu). 

The more I think about it, I lean towards adding a new button like your sketch. It reuses space that is not occupied, feels clear, and does not change the part of the toolbar that is consistent across all versions of the editor. 
<img width="991" alt="Screen Shot 2020-01-30 at 3 05 59 PM" src="https://user-images.githubusercontent.com/3409578/73485999-30a9f980-4372-11ea-8ddc-9eda7ad150b1.png">

That said, I am not sure it has to be a menu. One could imagine clicking that button and it opening the About Window with a Privacy Policy link. 

As far as the icon, while the "( ? )" may have connotations to our old help icon. I am can't think of something better... I don't feel the conical "( i )" is very localizable. We do use the "( ? )" as something that means "More Info". For example, in the new Join Flow uses these in places we have tooltips to provide more information. 

<img width="648" alt="Screen Shot 2020-01-30 at 3 14 10 PM" src="https://user-images.githubusercontent.com/3409578/73486456-33591e80-4373-11ea-8194-ed8864a54d78.png">


**About Window**
To me, adding the Privacy Policy as a link in the About window looks like a great direction. Might just make the text white and keep the underline, but that's the only detail. 

**Privacy Policy Window**
Looks good to me!

**Comment by cwillisf** [comment]
@carljbowman @kathymakes any preference between these two icons? Also, do you think the size, margins, etc. look good? I tried to match the margin on the other side of the Scratch logo. Thanks for your input!

![image](https://user-images.githubusercontent.com/7019101/73699421-9959e480-4698-11ea-9715-212f5c9b9e2e.png)

![image](https://user-images.githubusercontent.com/7019101/73699577-07061080-4699-11ea-827f-741a3ca7bf4f.png)

((Scratch Cat was here))

**Comment by carljbowman** [comment]
@cwillisf - It would be good to make the proportions similar to the "My Stuff" icon in the online editor. The dark blue is a result of hovering over the button, but thought it might be helpful to see.
<img width="89" alt="Screen Shot 2020-02-05 at 9 57 50 AM" src="https://user-images.githubusercontent.com/3409578/73853641-333ba180-47ff-11ea-820c-cde89419c434.png">

Here is a new icon that is in our standard 20px by 20px layout.
[About.svg.zip](https://github.com/LLK/scratch-desktop/files/4160212/About.svg.zip)

Mocks
<img width="1040" alt="Screen Shot 2020-02-05 at 10 10 29 AM" src="https://user-images.githubusercontent.com/3409578/73853984-c07ef600-47ff-11ea-94b2-04c6d3e2f40d.png">

Sizing with "Hover" state to see the full button.
<img width="992" alt="Screen Shot 2020-02-05 at 10 03 45 AM" src="https://user-images.githubusercontent.com/3409578/73853715-55352400-47ff-11ea-95bf-45159daa9168.png">
